language: haskell
ghc:
  - "8.2.2"

script:
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
  - cabal configure --enable-tests && cabal build
  - cabal test --test-option=--color
