language: c
cache:
  directories:
    - $HOME/.stack
    - $HOME/.local

before_install:
  - mkdir -p $HOME/.local/{bin,lib}
  - curl -sSL https://get.haskellstack.org/ | sh -s - -d $HOME/.local

script:
  - stack build && stack test
