name:        hdsk
version:     0.1.0.0
github:      "wbadart/hdsk"
license:     BSD3
author:      "Will Badart"
maintainer:  "wbadart (at) pm (dot) me"
copyright:   "2018 Will Badart"

synopsis:    Unified data science toolkit for Haskell and more
category:    Math

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - vector == 0.12.*
  - containers < 0.6
  - matrix >= 0.3
  - hashtables >= 1.2
  - hashable >= 1.2 && < 2
  - heap >= 1.0.4 && < 2

library:
  source-dirs: src
  exposed-modules:
    - Hdsk.Bins
    - Hdsk.Cluster
    - Hdsk.DecisionTree
    - Hdsk.DecisionTree.Information
    - Hdsk.Description
    - Hdsk.Metrics
    - Hdsk.NaiveBayes
    - Hdsk.NearestNeighbors
    - Hdsk.Numerical
    - Hdsk.Util
  ghc-options:
    - -Wall

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - hdsk
      - base >= 4.7 && < 5
      - vector == 0.12.*
      - hspec == 2.*
      - QuickCheck == 2.11.*

  # doctest:
  #   main:         RunDocTest.hs
  #   source-dirs:  test
  #   ghc-options:
  #     - -threaded
  #     - -rtsopts
  #     - -with-rtsopts=-N
  #   dependencies:
  #     - hdsk
  #     - doctest >= 0.2

benchmarks:
  # metrics:
  #   main: benchmark/Metrics.hs
  #   dependencies:
  #     - hdsk
  #     - matrix >= 0.3
  #     - criterion >= 1.4 && < 2
  uniq:
    main: benchmark/Uniq.hs
    dependencies:
      - hdsk
      - criterion >= 1.4 && < 2

description: |
    = Haskell Data Science Kit

    ![Build status](https://travis-ci.org/wbadart/hdsk.svg?branch=master)

    The Haskell Data Science Kit (/HDSK/) project is an attempt to create a
    well-documented, well-tested, and performant data science library implemented
    in the Haskell language.

    Sources suggest that in spite of huge potential for performance gains over
    current de facto methods [1], adoption of Haskell in the data science
    community lags for a variety of reasons, the greatest of which seems to be the
    dearth [2] of easy-to-use data science libraries (indeed, searching for
    "/data science/" on GitHub yields __14__ Haskell-language repositories and
    __5,807__ Python-language repositories [3]). This project seeks to mediate
    that issue by presenting a /unified/ (though modular) library of data science
    utilities which support the entire life-cycle of a data science project.

    __Disclaimer:__ At the time of writing, I am still a beginner in Haskell, and
    this project is as much about the above stated goal as it is about me learning
    and practicing Haskell itself and the software development ecosystem around it.
    So, I make no guarantees that I will give the most optimal or idiomatic
    solution to any given function (and in cases when I don't, pull requests are
    gladly welcomed!).

    1. https://izbicki.me/blog/hlearn-cross-validates-400x-faster-than-weka
    2. https://www.linkedin.com/pulse/haskell-data-science-good-bad-ugly-tom-hutchins
    3. https://github.com/search?q=data+science+language%3AHaskell&type=Repositories


    == Installation

    To use HDSK within your __stack__ project, you must add this repository to the
    @extra-deps@ list in @stack.yaml@. NOTE: this step will change once HDSK is
    released on Hackage.

    @
        extra-deps:
        - git: git@github.com:wbadart/hdsk.git
          commit: a52bed4216f607628e71594256dafd550ffe2d3e
    @

    The commit hash listed above is the most recent commit at the time of this writing.
    Be sure that the value you use is a recent enough to contain the features you
    need.

    The cabal file generated by stack has been checked in, so if you aren't using
    stack, and are only using cabal, the library can be installed from a fresh clone
    of the repository.


    == Usage

    Please see [wbadart.info/hdsk](https://wbadart.info/hdsk) for library documentation.
    Further project info, such as planned features, is made available on the
    wiki: https://github.com/wbadart/hdsk/wiki.


    == License

    You'll notice a key theme in this document has been __promoting adoption.__ As
    such, I'm developing and eventually releasing this project under the
    BSD-3-Clause [1] license, due to its general permissiveness. This is also
    one of the more popular licenses among the Haskell community [2].

    Please see [LICENSE](./LICENSE) for the full text.

    11. https://opensource.org/licenses/BSD-3-Clause
    12. https://wiki.haskell.org/How_to_write_a_Haskell_program
