name:        hdsk
version:     0.1.0.0
github:      "wbadart/hdsk"
license:     BSD3
author:      "Will Badart"
maintainer:  "wbadart (at) pm (dot) me"
copyright:   "2018 Will Badart"

synopsis:    Unified data science toolkit for Haskell and more
category:    Math
description: Please see the README on GitHub at <https://github.com/wbadart/hdsk>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - vector == 0.12.*
  - containers < 0.6
  - matrix >= 0.3
  - hashtables >= 1.2

library:
  source-dirs: src
  exposed-modules:
    - Hdsk.Cluster.KMeans
    - Hdsk.Description
    - Hdsk.Metrics
    - Hdsk.Bayesian.NaiveBayes
    - Hdsk.Bayesian.Bins
  ghc-options:
    - -Wall

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - hdsk
      - base >= 4.7 && < 5
      - vector == 0.12.*
      - hspec == 2.*
      - QuickCheck == 2.11.*

  # doctest:
  #   main:         RunDocTest.hs
  #   source-dirs:  test
  #   ghc-options:
  #     - -threaded
  #     - -rtsopts
  #     - -with-rtsopts=-N
  #   dependencies:
  #     - hdsk
  #     - doctest >= 0.2

benchmarks:
  metrics:
    main: benchmark/Metrics.hs
    dependencies:
      - hdsk
      - matrix >= 0.3
      - criterion >= 1.4 && < 2

  nb:
    main: benchmark/NB.hs
    dependencies:
      - hdsk
      - criterion >= 1.4 && < 2
