name:        hdsk
version:     0.1.0.0
github:      "wbadart/hdsk"
license:     BSD3
author:      "Will Badart"
maintainer:  "wbadart (at) pm (dot) me"
copyright:   "2018 Will Badart"

synopsis:    Unified data science toolkit for Haskell and more
category:    Math
description: Please see the README on GitHub at <https://github.com/wbadart/hdsk>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - vector == 0.12.*
  - containers >= 0.6.0.0 && < 0.7

library:
  source-dirs: src
  exposed-modules:
    - Hdsk.Description
    - Hdsk.Description.Generic
    - Hdsk.Bayesian.NaiveBayes
    - Hdsk.Bayesian.Bins
  ghc-options:
    - -Wall
    - -Wno-type-defaults

tests:
  hdsk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hdsk
      - base >= 4.7 && < 5
      - vector == 0.12.*
      - hspec == 2.*
      - QuickCheck == 2.11.*

benchmarks:
  generics:
    main: benchmark/GenericVsVector.hs
    dependencies:
      - hdsk
      - random == 1.1.*
      - criterion >= 1.4 && < 2
